/**
 * Desc:
 * @author 李锦涛
 * Created on 2026/9/19
 * Email: tao351992257@163.com
 */
export default class ComponentsName {
  /** ArkUI组件 **/
  static readonly COLUMN_COMPONENT_NAME = 'Column'
  static readonly ROW_COMPONENT_NAME = 'Row'
  /** 状态组件 **/
  static readonly STATE_LOCAL = '@Local装饰器'
  static readonly STATE_PARAM = '@Param装饰器'
  static readonly STATE_ONCE = '@Once装饰器'
  static readonly STATE_EVENT = '@Event装饰器'
  static readonly STATE_PROVIDER_CONSUMER = '@Provider与@Consumer装饰器'
  static readonly STATE_COMPUTED = '@Computed装饰器'
}